title = "JESUS IS THE LIFE"
theme = "contrast-hugo"
baseurl= "https://gm-mzv.github.io/bible-to-wolrd-hildegard/"

[params]
  minimal = false
  excerpts = false
  description = "bible-to-world"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10